apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-kubernetes
  namespace: homework-s09
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-kubernetes
  template:
    metadata:
      labels:
        app: hello-kubernetes
    spec:
      containers:
        - name: web
          image: nginx:1.27-alpine
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 2
            periodSeconds: 3
          resources:
            requests:
              cpu: 20m
              memory: 24Mi
            limits:
              cpu: 100m
              memory: 64Mi
